// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8t_XqBR4LH4klFZa8ep-0jLy1siHpgs',
    appId: '1:92803370851:web:8bdbcad70e0b28e8938d56',
    messagingSenderId: '92803370851',
    projectId: 'ipbp-statement-analyzer',
    authDomain: 'ipbp-statement-analyzer.firebaseapp.com',
    storageBucket: 'ipbp-statement-analyzer.firebasestorage.app',
    measurementId: 'G-8F8HMDXP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqbKgz5ypedGYeFOWEBD_izeNLGKoMiI',
    appId: '1:92803370851:android:e8eb5c82dead157c938d56',
    messagingSenderId: '92803370851',
    projectId: 'ipbp-statement-analyzer',
    storageBucket: 'ipbp-statement-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzhZ7seJyf2yaa1l8RRXISzS2Vqo5lETA',
    appId: '1:92803370851:ios:18051c75cd2b1533938d56',
    messagingSenderId: '92803370851',
    projectId: 'ipbp-statement-analyzer',
    storageBucket: 'ipbp-statement-analyzer.firebasestorage.app',
    iosClientId: '92803370851-9pggqi371btllim5is5qrsl6n2c94qmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.statementAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzhZ7seJyf2yaa1l8RRXISzS2Vqo5lETA',
    appId: '1:92803370851:ios:18051c75cd2b1533938d56',
    messagingSenderId: '92803370851',
    projectId: 'ipbp-statement-analyzer',
    storageBucket: 'ipbp-statement-analyzer.firebasestorage.app',
    iosClientId: '92803370851-9pggqi371btllim5is5qrsl6n2c94qmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.statementAnalyzer',
  );
}
